# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19d7c91c5e1a3423be40b6d955d8d461b602be351d5b0486a235f80b81ab9b874844dde3ed7f60cabcf7f6324ec55b1287af77ca12404261d721806a1b9b4e78

test:
  secret_key_base: 460644171a51ee5fecd1396dbd87b52c268b63b8333a11a2f7f940932eeaf35ee0147d46aa772abe4b384c295f30894fc95deaa4edb5359a89d3160a04163a1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
